python3 ASTARTraslados.py ./ASTAR-test/mapa01.csv 1
python3 ASTARTraslados.py ./ASTAR-test/mapa01.csv 2
python3 ASTARTraslados.py ./ASTAR-test/mapa01.csv 3
python3 ASTARTraslados.py ./ASTAR-test/mapa02.csv 1
python3 ASTARTraslados.py ./ASTAR-test/mapa02.csv 2
python3 ASTARTraslados.py ./ASTAR-test/mapa02.csv 3
python3 ASTARTraslados.py ./ASTAR-test/mapa03.csv 1
python3 ASTARTraslados.py ./ASTAR-test/mapa03.csv 2
python3 ASTARTraslados.py ./ASTAR-test/mapa03.csv 3
python3 ASTARTraslados.py ./ASTAR-test/mapa04.csv 1
python3 ASTARTraslados.py ./ASTAR-test/mapa04.csv 2
python3 ASTARTraslados.py ./ASTAR-test/mapa04.csv 3